apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-next-app
  description: Skeleton for a Next.js app.
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: team-cowboy
